# Generated by Django 5.2 on 2025-05-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("project_photo", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                (
                    "project_photo_1",
                    models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/"),
                ),
                (
                    "project_photo_2",
                    models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/"),
                ),
                (
                    "project_photo_3",
                    models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/"),
                ),
                ("url", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
